import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    title: {
        fontSize: 36,
        marginBottom: 16,
    },
    button: {
        alignItems: "center",
        backgroundColor: "#DDDDDD",
        padding: 10,
        marginTop: 10,
    },
    container: {
        marginBottom: 16,
        textTransform: 'uppercase',
        alignItems: 'center',
    },
    SkillContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems:'center',
        backgroundColor: 'black',
    },
    SkillHeader: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    SkillTitle: {
        fontSize: 36,
        color: 'white',
        fontFamily: "Arial",
    },
    SkillBody: {
        flex: 5,
        margin: 10,
        marginBottom:20,
        height:50,
        borderColor: 'black',
        borderWidth: 1,
        backgroundColor: 'white',
        borderRadius: 2,
        padding: 5,
        justifyContent:'center',
        width:500,
    },
    SkillList: {
        flex: 5,
        flexDirection: 'row',
        fontSize: 48,
        padding: 20,
        justifyContent: 'flex-start',
        textTransform: 'uppercase',
    },
    Skill: {
        flex: 1,
        marginTop: 10,
        height: 50,
        borderColor: 'black',
        borderWidth: 1,
        backgroundColor: 'white',
        borderRadius: 2,
        padding: 5,
    },
    SkillText: {
        fontSize: 20,
        marginBottom: 5,
        fontFamily:"sans",
    },
    ProgressView: {
        marginBottom: 10,
    },
    contact: {
        flex: 1,
        marginLeft: 10,
        borderColor: 'black',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 10,
    },
    contactHeader: {
        justifyContent: 'center',
        fontSize: 30,
        marginBottom: 20,
    },
    username: {
        marginTop: 10,
        height: 40,
        width: 350,
        borderWidth: 1,
        borderColor: '#000',
        borderRadius: 2,
        padding: 10,
    },
    message: {
        marginTop: 10,
        height: '30%',
        width: 350,
        borderWidth: 1,
        borderColor: '#000',
        borderRadius: 2,
        padding: 5,
    },
    submitButton: {
        marginTop: 20,
        width: 200,
        height: 40,
        borderRadius: 20,
        borderColor: '#000',
        borderWidth: 0.5,
        backgroundColor: 'black',
        justifyContent: 'center',
        alignItems: 'center',
    }
});
